name: segbench
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-image
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pyarrow
  - tifffile
  - zarr
  - dask
  - geopandas
  - shapely
  - pyvips
  - pytest
  - mypy
  - pytorch
  - torchvision
  - pip
  - pip:
      - scanpy
      - squidpy
      - anndata
      - spatialdata
      - spatialdata-io
      - spatialdata-plot
      - cellpose
